# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 04:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=20, null=True)),
                ('city', models.CharField(blank=True, max_length=250, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('locale', models.CharField(blank=True, max_length=10, null=True)),
                ('ip', models.GenericIPAddressField()),
                ('link', models.URLField()),
                ('profile_picture', models.URLField(default='laskdfj')),
                ('photo_id_front', models.ImageField(default='pic_folder/None/no-img', upload_to=b'')),
                ('photo_id_back', models.ImageField(default='pic_folder/None/no-img', upload_to=b'')),
                ('mobile_no', models.IntegerField(default=9999)),
                ('UUID', models.UUIDField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
