# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 06:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceNature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_location', models.CharField(choices=[('studio', 'studio'), ('doorstep', 'doorstep')], max_length=20)),
                ('name', models.CharField(max_length=25)),
                ('desc', models.TextField()),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ('service_name',),
            },
        ),
        migrations.AddField(
            model_name='servicenature',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.ServiceType'),
        ),
    ]
