# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 00:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicenature',
            name='service_location',
            field=models.CharField(choices=[('studio', 'Studio'), ('doorstep', 'Doorstep')], max_length=20),
        ),
    ]
