# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 14:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('franchise', '0002_auto_20170202_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='franchise',
            name='city',
        ),
        migrations.RemoveField(
            model_name='services',
            name='franchise',
        ),
        migrations.RemoveField(
            model_name='services',
            name='modified',
        ),
        migrations.AddField(
            model_name='franchise',
            name='members',
            field=models.ManyToManyField(through='franchise.Services', to='franchise.City'),
        ),
        migrations.AddField(
            model_name='services',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='franchise.City'),
        ),
        migrations.AddField(
            model_name='services',
            name='date_joined',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='franchise.Franchise'),
        ),
        migrations.AddField(
            model_name='services',
            name='invite_reason',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
