# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 14:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20170131_0043'),
        ('franchise', '0003_auto_20170202_1438'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='group',
            new_name='franchise',
        ),
        migrations.AlterUniqueTogether(
            name='services',
            unique_together=set([('city', 'franchise', 'services')]),
        ),
    ]
