# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franchise', '0004_auto_20170202_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='franchise',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='franchise',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='franchise',
            name='landline_no',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='franchise',
            name='mobile_no',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='franchise',
            name='pincode',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
