# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 23:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('franchise', '0007_auto_20170203_0331'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'permissions': (('view_services', 'Can view'),)},
        ),
    ]
