# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 09:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('franchise', '0009_services_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='franchise',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='franchise',
            name='lat',
            field=models.DecimalField(decimal_places=3, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='franchise',
            name='lon',
            field=models.DecimalField(decimal_places=3, max_digits=9, null=True),
        ),
    ]
